### ISSUE TITLE
Broken _msearch

### ISSUE THREAD

**Issue by psaiz** [sscarduzio/elasticsearch-readonlyrest-plugin#274] opened 2017-09-27 08:40 UTC
Hi Simone, 

We are running readonlyrest 5.5.2.1.16.11, and I'm seeing something quite weird with the msearch. Note the following queries:

```
[]# cat /tmp/not_exist 
{"index":["perfmon_index_does_not_exist"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
[]# cat /tmp/query_works 
{"index":["perfmon_endpoint_requests"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"match_all":{}}, "size":0}
[]# cat /tmp/empty_index 
{"index":[".kibana"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
```

If I do the queries independently, they work as expected:

```
[]# cat /tmp/not_exist  | curl  -X POST localhost:9200/_msearch --data-binary "@-"
{"responses":[{"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]},"status":200}]}

[]# cat /tmp/query_works    | curl -X POST localhost:9200/_msearch --data-binary "@-"
{"responses":[{"took":24,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":47,"max_score":0.0,"hits":[]},"status":200}]}

[]# cat /tmp/empty_index  | curl -X POST localhost:9200/_msearch --data-binary "@-"
{"responses":[{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]},"status":200}]}

```

Note the number of hits on the second one. If I do two together, it still works

```
# cat /tmp/not_exist /tmp/query_works    | curl -X POST localhost:9200/_msearch --data-binary "@-"
{"responses":[{"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]},"status":200},{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":47,"max_score":0.0,"hits":[]},"status":200}]}
```
Note again the 47.

If I do 3, it does not work:

```
# cat /tmp/not_exist /tmp/query_works  /tmp/empty_index   | curl   -X POST localhost:9200/_msearch --data-binary "@-"
{"responses":[{"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]},"status":200},{"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]},"status":200},{"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]},"status":200}]}
```

Note the hits is 0, and that the _shards is also 0.

If I disable the ROR configuration, then it works as expected. Could you please take a look?

Cheers,
 pablo

**Comment by sscarduzio** [comment] 2017-09-28 07:02
Hello Pablo,

Thanks for reporting this and distilling a simple reproducer. Very helpful!
In the meanwhile I investigate this, can you tell me if this is a new bug that was not there in the old 1.14.0 you were using until last week?

**Comment by sscarduzio** [comment] 2017-09-28 09:39
Also, what is the minimal configuration or ROR to make this behave like this?

**Comment by sscarduzio** [comment] 2017-09-28 09:52
OK this is my test case
```yaml
readonlyrest:
    prompt_for_basic_auth: false
    audit_collector: true

    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana
      verbosity: error
```
These are the files I created:

```bash
(env) sscarduzio@hilbert:/tmp$ cat not_exist
{"index":["perfmon_index_does_not_exist"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
(env) sscarduzio@hilbert:/tmp$ cat query_works
{"index":[".kibana"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"match_all":{}}, "size":0}
(env) sscarduzio@hilbert:/tmp$ cat empty_index
{"index":[".kibana"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
```
Notice I changed the "query_works" index to point to `.kibana`, as I don't have that perfmon index in my environment.

Then I wrote this script that shows the hits total of each search response
```bash
for i in not_exist query_works empty_index "not_exist query_works empty_index"; do echo;echo; echo $i; cat $i | curl -s  -ukibana:kibana -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; done
```
The result is this:
```bash
not_exist
0


query_works
3


empty_index
0


not_exist query_works empty_index
0
3
0
```

So the 3 is there in `query_works` and in all three queries bundled. So could not reproduce.

**Comment by sscarduzio** [comment] 2017-09-28 09:53
HOWEVER, as soon as I introduce a indices rule to the mix:
```yaml
    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana
      indices: [".kibana"]
      verbosity: error
```
The result changes:

```

not_exist
0


query_works
3


empty_index
0


not_exist query_works empty_index
0
0
0
```

So the issue is within the indices rule. PROGRESS!

**Comment by psaiz** [comment] 2017-09-28 12:03
Hi Simone, 

Thanks for looking into this. I don't think that this was there on 1.1.14. 

Concerning the minimal rules, the rule that was matching my cases as also with indices. 
Cheers, 
pablo

**Comment by sscarduzio** [comment] 2017-09-28 15:27
OK I identified why this happens.

Right now, if we detect that the current request refers to **at least one** non-existent index (without wildcards), we know ES will discard the request with a 404. For some reason, we also call a setIndices(someNonExistingIndex) just "to be safe". And for a Get or a Search, this is  not an issue.

But if you set the non existing index in a MSearch/Mget, ROR goes through all sub requests and sets them to the same non-existent index. And this gives what your test shows.

## SOLUTION
If we discover a request having at least one non-wildcard index which does not exist, immediately let it through (expecting ES to shoot a 404 anyway) only **if this is not a CompositeIndicesRequest (Mget/Msearch/Bulk)**.

Should the request at hand be composite, just ignore the non-existing index in the further logic (as ES will treat it as a zero-result sub-response).

**Comment by psaiz** [comment] 2017-09-28 15:34
Thanks a lot for the very fast debugging and fixing the issue! We'll test the new version, and let you know.

**Comment by sscarduzio** [comment] 2017-10-04 20:57
Pablo, all good with this?

**Comment by psaiz** [comment] 2017-10-06 07:47
Hi Simone, 

I'm afraid that this is still happening with 1.16.12, at least for some combination of queries.  Let me see if I can reproduce it with a simple example.

Cheers,
 pablo

**Comment by psaiz** [comment] 2017-10-06 08:23
Ok, here we go:
```
[root@esperfmons01 tmp]# cat /tmp/no_match 
{"index":["perfmon_logstash-apacheaccess*"]}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
[root@esperfmons01 tmp]# cat /tmp/broken 
{"index":["perfmon_endpoint_requests"]}
{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"size":0}
[root@esperfmons01 tmp]# cat /tmp/empty_index 
{"index":[".kibana"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
[root@esperfmons01 tmp]# for i in no_match broken empty_index "no_match broken empty_index"; do echo;echo; echo $i; cat $i | curl -s  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; done
 

no_match
0


broken
47


empty_index
0


no_match broken empty_index
0
354217807
0
```

**Comment by psaiz** [comment] 2017-10-06 08:35
The 354217807 looks like the number of documents in the perfmon_logstash-apacheaccess*

**Comment by sscarduzio** [comment] 2017-10-06 09:29
Hey Pablo, thanks for testing this. I re-reproduced the bug and found another issue. Last time I verified the fix with the wrong test case. My bad, I should have caught this too before.

```bash
$ for i in not_exist query_works empty_index "not_exist query_works empty_index"; do echo;echo; echo $i; cat $i | curl -s  -ukibana:kibana -X POST -k https://localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; done


not_exist
0


query_works
4


empty_index
0


not_exist query_works empty_index
0
4
0
```

**Comment by schwicke** [comment] 2017-10-09 13:34
Hi, Simone,
I'd like to cross check with you: we've picked 1.16.12-pre3, and we still see the issue, apparently. Was this supposed to be fixed in this version ? Thanks!

**Comment by sscarduzio** [comment] 2017-10-10 08:32
Hey @schwicke!
Wait, first of all are you after all using the sub requests scan logic? As this is a bug inside that feature.

And yes, the pre3 contains the change that made my test pass as the comment above. Using some test query files similar to the ones originally proposed initially by Pablo (see the message I edited above including my test query files)

Looking closer, the second example Pablo showed seems different though, isn't it? 
```
# cat /tmp/broken 
{"index":["perfmon_endpoint_requests"]}
{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"size":0}
```

In his test, the query contained in the "broken" file - when ran alone - return 47 results when he expected  354217807 results. Is that right?

**Comment by psaiz** [comment] 2017-10-10 11:11
Hi Simone, 

It is the other way around. Running the query  by itself returned the 47 entries (as expected). Running it with the _msearch returned the wrong values. It looks like it is done the query in the wrong index pattern.

Cheers, 
pablo

**Comment by sscarduzio** [comment] 2017-10-11 13:47
@psaiz ok, but how comes you are still using still this doomed sub-request inspection feature? I'm literally removing it as it's crippling performance, and has little to none benefit.

**Comment by schwicke** [comment] 2017-10-11 13:57
Hi, Simone,
we are running with 

" -Dcom.readonlyrest.subreq.introspection=false -Dcom.readonlyrest.kibana.metadata=false" so the sub-request checking should be disabled, right ?

**Comment by sscarduzio** [comment] 2017-10-11 14:19
Oh ok, this changes everything.

I’m soon going to push a substantial refactor of RoR after having removed all the sub request logic, shrunk the ES-specific code to the bare minimum, and removed a ton of unbelievably pointless contributed code. 

Tomorrow I’m going to add more integration tests, including some specific to this issue. 

All this in preparation to RoR 2.0 which will be a rewrite of the “core” subproject including connectors and configuration model, hopefully in Scala, hopefully easier to test.

**Comment by sscarduzio** [comment] 2017-10-11 14:20
Oh ok, this changes everything.

I’m soon going to push a substantial refactor of RoR after having removed all the sub request logic, shrunk the ES-specific code to the bare minimum, and removed a ton of unbelievably pointless contributed code. 

Tomorrow I’m going to add more integration tests, including some specific to this issue. 

All this in preparation to RoR 2.0 which will be a rewrite of the “core” subproject including connectors and configuration model, hopefully in Scala, hopefully easier to test.

**Comment by schwicke** [comment] 2017-10-11 14:26
Happy to test again with the new version.

**Comment by sscarduzio** [comment] 2017-10-16 16:25
FYI I wrote this test (which passes) about this issue. 

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/integration-tests/src/test/scala/tech/beshu/ror/integration/MSearchTests.scala#L18

**Comment by psaiz** [comment] 2017-10-24 08:27
Hi Simone, 

Would you mind reopening the ticket until the issue is understood and solved? We still see the wrong behaviour.

Cheers, 
pablo

**Comment by schwicke** [comment] 2017-10-31 14:21
I've upgraded to 1.16.13-pre1, and we can reproduce it with this latest version as well.

**Comment by sscarduzio** [comment] 2017-10-31 15:53
Thanks @schwicke, I can build a reproducer test for it today. Can you share your most elementary test case you have at hand?

**Comment by sscarduzio** [comment] 2017-10-31 18:20
@psaiz shared this, but it's not clear what are the preconditions and the desired output.

```
[root@esperfmons01 tmp]# cat /tmp/no_match 
{"index":["perfmon_logstash-apacheaccess*"]}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
[root@esperfmons01 tmp]# cat /tmp/broken 
{"index":["perfmon_endpoint_requests"]}
{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"size":0}
[root@esperfmons01 tmp]# cat /tmp/empty_index 
{"index":[".kibana"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
[root@esperfmons01 tmp]# for i in no_match broken empty_index "no_match broken empty_index"; do echo;echo; echo $i; cat $i | curl -s  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; done
 

no_match
0


broken
47


empty_index
0


no_match broken empty_index
0
354217807
0
```

**Comment by psaiz** [comment] 2017-11-01 09:26
Hi Simone, 

The desired output is that the result of the individual queries is the same if done with the _msearch (so, the output of 'no_match broken empty_index' should be '0 47 0' instead of '0 354217807 0').

The preconditions are that the index 'perfmon_endpoint_requests' has 47 entries, and behind the first index_pattern (perfmon_logstash-apacheaccess*), there are 354217807 entries.

Cheers, 
pablo

**Comment by sscarduzio** [comment] 2017-11-02 19:07
@psaiz I finally created[ a test for this](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/integration-tests/src/test/scala/tech/beshu/ror/integration/MSearchTEST2_Tests.scala). Which passes (unfortunately?).  

I will run through it for you. 

### Settings YAML
```yml
    readonlyrest:
          access_control_rules:
          - name: "CONTAINER ADMIN" # <-- unrelated to test, disregard
            type: allow
            auth_key: admin:container
        
          - name: "::KIBANA-SRV::" # <--- just some random user allowed to use these indices
            auth_key: kibana:kibana
            indices: ["perfmon_endpoint_requests","perfmon_logstash-apacheaccess*"]
            verbosity: error
```
## Initialization
 
1. Create an empty index called "emptyIndex" without documents.
2. Create "perfmon_endpoint_requests" index with 1 doc in it
3. Create "perfmon_logstash-apacheaccess1" index with 2 doc in it


## Tests

### test No match
msearch 
```
{"index":["perfmon_logstash-apacheaccess*"]}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
```
**expected result**
0 documents


### test "broken" 
msearch (logged in as kibana user) 
```
{"index":["perfmon_endpoint_requests"]}
{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"size":0}
```
**expected result**
1 documents


### test "emptyIndex" 
msearch (logged in as kibana user)
```
{"index":["emptyIndex"],"ignore_unavailable":true,"preference":1506497937939}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
```
**expected result**
0 documents


### test  all together (in order) 
msearch (logged in as kibana user)
``` 
      {"index":["perfmon_logstash-apacheaccess*"]}
      {"query":{"bool":{"must_not":[{"match_all":{}}]}}}
      {"index":["perfmon_endpoint_requests"]}
      {"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"size":0}
      {"index":["emptyIndex"],"ignore_unavailable":true,"preference":1506497937939}
      {"query":{"bool":{"must_not":[{"match_all":{}}]}}}
```
**expected result**
0 documents
1 documents (and not 3)
0 documents


Please advise if I'm missing some detail or concept, because this is passing form me.

**Comment by psaiz** [comment] 2017-11-08 15:48
Hi Simone, 

One difference between the test case and what I see is that I don't have a '"perfmon_logstash-apacheaccess1" index with 2 doc in it'. Instead, it is two indices with one document each. Also, please note that in your example it is a bit strange that hte query to 'emptyIndex' works, since the user doesn't have access to that directory.


I can still reproduce this bug with  5.5.2.1.16.13-1 

1. Populate the indices:
```
 curl -X PUT localhost:9200/perfmon_endpoint_requests/my_type/1 -d '{"hello":"world"}'
 curl -X PUT localhost:9200/perfmon_logstash-apacheaccess_1/my_type/1 -d '{"hello":"world"}'
 curl -X PUT localhost:9200/perfmon_logstash-apacheaccess_2/my_type/1 -d '{"hello":"world"}'
```
2. Single rule:
```
  - name: es-internal perfmon_writer
    type: allow
    groups:
    - perfmon_rw
    indices:
    - perfmon*
    verbosity: error
```
3. Write the three queries:
```
[root@esints01 ~]# cat /tmp/empty_index 
{"index":[".kibana"]}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
[root@esints01 ~]# cat /tmp/broken 
{"index":["perfmon_endpoint_requests"]}
{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"size":0}
[root@esints01 ~]# cat /tmp/no_match 
{"index":["perfmon_logstash-apacheaccess*"]}
{"query":{"bool":{"must_not":[{"match_all":{}}]}}}
```
4. Queries, one by one. They all behave as expected:
```
[root@esints01 ~]# cat /tmp/empty_index      | curl -s  -H 'X-Forwarded-User: perfmon'  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; 
parse error: Invalid numeric literal at line 1, column 6
[root@esints01 ~]# cat /tmp/broken      | curl -s  -H 'X-Forwarded-User: perfmon'  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; 
1
[root@esints01 ~]# cat /tmp/no_match      | curl -s  -H 'X-Forwarded-User: perfmon'  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; 
0
```
5.  Do the three queries in one. 
```
[root@esints01 ~]# cat /tmp/empty_index  /tmp/no_match /tmp/broken     | curl -s  -H 'X-Forwarded-User: perfmon'  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; 
0
0
3
```
Note that it returns 3 documents, instead of 1. If I do only two of the queries (even if I do it multiple times) it still works:

```

[root@esints01 ~]# cat /tmp/broken  /tmp/broken  /tmp/broken  /tmp/no_match  | curl -s  -H 'X-Forwarded-User: perfmon'  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; 
1
1
1
0
```

As soon as I put the last one, it breaks:

```
[root@esints01 ~]# cat /tmp/broken  /tmp/broken  /tmp/broken  /tmp/no_match /tmp/empty_index   | curl -s  -H 'X-Forwarded-User: perfmon'  -X POST localhost:9200/_msearch --data-binary "@-" |jq .responses[].hits.total; 
3
3
3
0
0
```




Hope that helps!

cheers,
 pablo

**Comment by fastestdebugger** [comment] 2017-11-13 15:11
I am seeing incorrect results for _msearch as well where RoR is configured to allow access to at least one index in the _msearch request but not all. So the result comes back sometimes (depending on the indexes) with results from other accessible indices in the _msearch in place of the indices that are protected. One thing to note is all our indices are aliased and time based so they are effectively the same as wildcards.

After looking at the code, I think what is happening is the IndicesSyncRule expands and filters each request in a _msearch and puts all accessible indices in one list. Then later in the RequestInfo.writeIndices method the entire list of all accessible indices gets set on all searches effectively changing each search in the _msearch. So the searches potentially end up tainted with other indices.

I am working on a good test case but I am not sure how to go about a fix at this point, so I thought I would throw this out there.

**Comment by sscarduzio** [comment] 2017-11-13 19:29
I probably should just return NO_MATCH if the request refers to a mix of  allowed/not-allowed indices AND THIS IS A BULK REQUEST...

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/tech/beshu/ror/acl/blocks/rules/impl/IndicesSyncRule.java#L129

**Comment by sscarduzio** [comment] 2017-11-13 23:09
So I found a fundamental problem: 
1. One MultiSearch request arrives containing two SearchRequest: the first refers to index "a", the second to index "b"
2. ROR calls the indices method on the MultiSearch: it gets ["a", "b"]
3. ROR decides that "b" is not allowed, but "a" can be queried.

**CURRENT WRONG BEHAVIOUR**
 ROR keeps the two SearchRequests, but overwrites "a" into their indices field

**WHAT SHOULD HAPPEN (1)**
ROR should drop the while MultiSearch


**WHAT SHOULD HAPPEN (2)**
ROR should go through all the sub-requests and discard the one referred to "b"

I'm afraid the expected result is the second, so ROR needs a good bunch of ES-version specific code to handle this (a bit like the one we had for inspecting through the bulk index).

**Comment by ld57** [comment] 2017-11-14 08:30
Hi,

it is the case if : 
- in kibana you defined an index patter like log*
- and in ES you have indices log-apache* and log-paloalto*
- and the user is authorized for log-paloalto* but not to log-apache*

am I right?

**Comment by sscarduzio** [comment] 2017-11-14 18:46
UPDATE: I might have found a way to take care of this **without** rebuilding that brittle castle of cards we used to have for sub-request inspection. Will commit something soon

**Comment by sscarduzio** [comment] 2017-11-14 21:39
OK guys, I have something for you: a more accurate variant of the (2).
@psaiz, @fastestdebugger: have a look at this new block handling MultiSearchRequest:
 
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/a47ac1bc4c08d8ffe7d5d6ae3b16ce0622d02597/es54x/src/main/java/tech/beshu/ror/es/RequestInfo.java#L358

**Comment by fastestdebugger** [comment] 2017-11-15 00:33
I love your solution with sending back empty results for the inaccessible indices. It won't completely fix our setup unfortunately because we use aliases instead of wildcards. For instance, we install in kibana something like project_a which is an alias for indices project_a_v1_2017 and project_a_v1_2016 and then we can have another alias for project_b with similar indices and so on. So the aliases won't match any of the indices in the newIndices set.

Is it possible to call expandIndices for each SearchRequest and compare those indices to the list of newIndices? Seems like that would work for all cases.

**Comment by sscarduzio** [comment] 2017-11-15 18:09
Yeah good observation! This is a very delicate issue, another pair of eyes is really good to have.

**Comment by sscarduzio** [comment] 2017-11-19 00:43
Hey guys, I spent some time on this. The aliases should be covered now, and also the MultiGet (in addition to the MultiSearch)

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/es54x/src/main/java/tech/beshu/ror/es/RequestInfo.java#L355

**Comment by fastestdebugger** [comment] 2017-11-19 03:44
Looks like it will work in our setup, I will try it out soon. Good thinking on the MultiGet. Thanks.

**Comment by ld57** [comment] 2017-11-19 10:16
Thanks @sscarduzio !!

**Comment by psaiz** [comment] 2017-11-20 10:59
Hi @sscarduzio, 

Thanks a lot for debugging and fixing this issue! I confirm that with the latest version, the _msearch works as expected.

**Comment by sscarduzio** [comment] 2017-11-20 14:24
Guys, this is great news! Thanks Pablo for reporting this and everyone else involved. 🙏

**Comment by schwicke** [comment] 2017-11-20 14:35
@sscarduzio any idea if there is any performance impact ? Would that only affect _msearch or also other operations? Thanks!!!

**Comment by sscarduzio** [comment] 2017-11-20 21:36
@schwicke this new code change is very specific to msearch and mget. 

If the mget/msearch contain a lot of sub-requests,  there will be quite a bunch of method calls for each sub request. And all of them will do a whole bunch of checks and eventually look up into the local node's "aliasAndIndexLookup" SortedMap.

I could  introduce a caching mechanism in my code so I could potentially reduce the number of concreteIndex/Alias resolutions IFF you foresee there's a high probability a multiget/multisearch will contain the same indices field in many sub requests. 

However the caching mechanism cannot span beyond the scope of the local HTTP request, because the list of indices and aliases could change and invalidating entries in such cache would go well beyond the scope of ROR.

**Closed** 2019-12-28 18:17 UTC
