### ISSUE TITLE
Question: when is the filter called?

### ISSUE THREAD

**Issue by pciccarese** [sscarduzio/elasticsearch-readonlyrest-plugin#35] opened 2016-03-30 15:04 UTC
I wrote some code to do dynamic indices aliasing. The idea is very simple: I get an index (ex: paolo) and I dynamically check for what indices I have access to and I replace 'paolo' with such list (ex: idx1, idx2). I run this code after the current indices filter is executed and I specify in the configuration that only acceptable index is 'paolo'.

When I tried though, I would get blocked. It turns out the indices filter is called twice. The first time (with index 'paolo') would validate. While the second one (with the indices idx1 and idx2) would fail as it does not meet the 'paolo' requirement. 

Simone, do you know why the filter is called twice?

**Comment by sscarduzio** [comment] 2016-03-30 15:17
Interesting, no idea. I will try to put some printf and hopefully see what and why this happens.  BTW, thanks Paolo for the features and insights you are contributing to this project!

**Comment by sscarduzio** [comment] 2016-03-30 15:57
Can't reproduce, mind sharing the conf file?

**Comment by pciccarese** [comment] 2016-03-30 15:59
Sure (it includes aliases):
```
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    access_control_aliases:

    - in: paolo
      out: [helloworld]

    access_control_rules:

    - name: Accept all requests from localhost
      type: allow
      hosts: [127.0.0.1]
      #indices: [paolo]

    - name: Accept only GETs from other host
      type: allow
      methods: [GET]
      indices: [translational]
```

**Comment by sscarduzio** [comment] 2016-03-30 16:13
Copied your conf exactly, sent a few requests to match both the blocks, my printf in the "IndicesRule.match" function prints just once.

The only thing I manage to print twice is if I add a printf in the upper part of the IndicesRule constructor, as it's called for every block.

**Comment by pciccarese** [comment] 2016-03-30 19:22
It might be a regression on my side. 

If (in IndexLevelActionFilter) I change this:
```
if (exitResult.isMatch() && exitResult.getBlock().getPolicy() == Block.Policy.ALLOW) {
      return true;
}
```

To:
```
if (exitResult.isMatch() && exitResult.getBlock().getPolicy() == Block.Policy.ALLOW) {
      logger.info("[readonlyrest] Request passed");
      return true;
    }
```
The logger prints always twice.

**Comment by pciccarese** [comment] 2016-03-30 20:52
I am not 100% sure but I believe this is the problem with 2.2.0:
https://github.com/elastic/elasticsearch/issues/14577

It might have been fixed in 2.3.0:
https://github.com/elastic/elasticsearch/pull/16758

Although I am not completely sure yet.

**Comment by sscarduzio** [comment] 2016-03-31 10:44
That would explain why I could not reproduce :)

**Comment by pciccarese** [comment] 2016-03-31 12:13
If that is the case, what I was trying to implement will not be working the same for 2.2.0. Which is a little disappointing. @sscarduzio I will try to outline my game plan in the next few days  to see if these are features you are interested in adding to the plugin. And we will go from there.

**Comment by sscarduzio** [comment] 2016-03-31 14:00
this 2.2.0 sounds like a really crappy release for readonly rest plugin. Not only your filter won't work, but all the filters will be inefficient and produce double logging. We could probably skip that build and  have a warning in the docs about our reasons. Thoughts?

PS: Looking forward to seeing what you're up to, @pciccarese :)

**Comment by pciccarese** [comment] 2016-03-31 17:55
I've tested the same codebase with 2.3.0 and the problem is gone. Which confirms that was the problem.

**Comment by sscarduzio** [comment] 2016-04-01 17:00
Closing this as it's an ES bug. Thanks for investigating on this @pciccarese

**Closed by sscarduzio** 2016-04-01 17:00 UTC
